// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ult/config"
	"ult/internal/api"
	"ult/internal/app"
	"ult/internal/data"
	"ult/internal/data/repo"
	"ult/internal/router"
	"ult/internal/server"
	"ult/internal/service"
	pkgapp "ult/pkg/app"
)

func initApp(conf *config.Config, tools *app.Tools) (*pkgapp.App, func(), error) {
	dataData, cleanup := data.NewData(conf, tools)
	testRepo := repo.NewTestRepo(dataData)
	heartbeatService := service.NewHeartbeatService(testRepo, tools)
	heartbeatHandler := api.NewHeartbeatHandler(heartbeatService, tools)
	httpRouter := router.NewHTTPRouter(heartbeatHandler)
	httpServer := server.NewHTTPServer(conf, tools.Logger(), httpRouter)
	app := newApp(conf, tools.Logger(), httpServer)
	return app, func() {
		cleanup()
	}, nil
}
