// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ult/config"
	"ult/internal/api"
	"ult/internal/app"
	"ult/internal/data"
	"ult/internal/data/repo"
	"ult/internal/router"
	"ult/internal/server"
	"ult/internal/service"
	app2 "ult/pkg/app"
	"ult/pkg/logger"
)

// Injectors from wire.go:

func initApp(conf *config.Config, tools *app.Tools) (*app2.App, func(), error) {
	logger := provideLogger(tools)
	dataData, cleanup := data.NewData(conf, tools)
	dataRepo := data.NewDataRepo(dataData)
	testRepo := repo.NewTestRepo(dataData)
	healtbeatService := service.NewHeartbeatService(dataRepo, testRepo, tools)
	heartbeatInterface := api.NewHeartbeatHandler(healtbeatService, tools)
	httpRouter := router.NewHTTPRouter(heartbeatInterface)
	httpServer := server.NewHTTPServer(conf, logger, httpRouter)
	appApp := newApp(conf, logger, httpServer)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

func provideLogger(tools *app.Tools) *logger.Logger {
	return tools.Logger()
}
